mindmap
  root((1 - Spacial Descriptions ))
    
    1.0 Overview
        block-beta id1("Introduces the notions of links, joints, base and end-effector of a robotic manipulator. ")
        block-beta id1("Introduces sets of spacial parameters that describe the position and orientation of the configuration of the manipulator structure.")

    1.1. Manipulator Structure
        1.1.0 Definitions
            block-beta id1("i. Manupulator or Robot - Sequence of rigid body links that are connected together via joints. ")
            block-beta id1("ii .Base - First link and is fixed in the environment of the robot. ")
            block-beta id1("iii. End-Effector - Last link and is the part that interacts with other objects in the environment i.e gripper")

            block-beta id1("iv. Manipulator's config is defined by its joints positions.")
            block-beta id1("v. End effector's config is described by it's position and orientation.")
            block-beta id1("vii. Forward Kinematics - The model describing the relationships between the manipulator config and the end effector config ")

            block-beta id1("viii. Prismatic Joints - Provide Motion between links.")
            block-beta id1("viii. Revolut Joints - Provide rotational motion.")

            block-beta id1("ix. Config description - Manipulator had       .")

        1.1.1 Generalised Coordinates
        1.1.2 Joint and Operational Coordinates
        1.1.3 Position and Orientation of Rigid Bodies
        1.1.4 Rotation Matrix
    1.2. Transformations
        1.2.1 Pure Rotation Transformation
        1.2.2 Pure Translation Transformation
        1.2.3 General Transalation
        1.2.4 Homogenous Transformation
        1.2.5 Transforms as Operators
        1.2.6 Inverse Transforms
        1.2.7 Transform Multiplication
        1.2.8 The Transform Equation
    1.3. Configuration Representations
                1.3.1 Direction Cosines
                1.3.2 Euler and Fixed Angle Representation
                1.3.3 Inverse of an Orientation Representation
                1.3.4 Equivalent Angle-Axis Representation
                1.3.5 Euler parameters