---
id: a77cece5-331f-4259-ab7e-d59cac931bdf
---
mindmap
  root((Manipulators/Robots))
    1.Spacial Descriptions 
      Overview
        %% block-beta id1("Introduces the notions of links, joints, base and end-effector of a robotic manipulator. ")
        %% block-beta id1("Introduces sets of spacial parameters that describe the position and orientation of the configuration of the manipulator structure.")
      Definitions
          %% block-beta id1("Manupulator or Robot - Sequence of rigid body links that are connected together via joints. ")
          %% block-beta id1("Base - First link and is fixed in the environment of the robot. ")
          %% block-beta id1("End-Effector - Last link and is the part that interacts with other objects in the environment i.e gripper")
      1.1. Manipulator Structure
        %% 1.1.1 Generalised Coordinates
        %% 1.1.2 Joint and Operational Coordinates
        %% 1.1.3 Position and Orientation of Rigid Bodies
        %% 1.1.4 Rotation Matrix
      1.2. Transformations
        %% 1.2.1 Pure Rotation Transformation
        %% 1.2.2 Pure Translation Transformation
        %% 1.2.3 General Transalation
        %% 1.2.4 Homogenous Transformation
        %% 1.2.5 Transforms as Operators
        %% 1.2.6 Inverse Transforms
        %% 1.2.7 Transform Multiplication
        %% 1.2.8 The Transform Equation
      1.3. Configuration Representations
        %% 1.3.1 Direction Cosines
        %% 1.3.2 Euler and Fixed Angle Representation
        %% 1.3.3 Inverse of an Orientation Representation
        %% 1.3.4 Equivalent Angle-Axis Representation
        %% 1.3.5 Euler parameters

    2.Direct Kinematics
      2.1 Introduction
      2.2 Link Descriptions
      2.3 Conventions for First and Last Link
      2.4 Attaching Frames to links
      2.5 Propagation of Frames
      2.6 Kinematics of Manupulators
      2.7 Direct Kinematics

    3.Inverse Kinematics
      3.1 Introduction
      3.2 Closed Form Solutions
      3.3 Pieper's Solution
      3.4 Existence of Solution
      3.5 Workspace of the Manipulator
      3.6 Number of Solutions

    4.The Jacobian
      4.1 Introduction
      4.2 Differential Motion
      4.3 Basic Jacobian
      4.4 Linear/Angular Motion
      4.5 Combined Linear and Angular Motion
      4.6 Jacobian - Velocity Propagation
      4.7 Jacobian - Explicit Form
      4.8 Kinematic Singularities
      4.9 Jacobian at Wrist/End-Effector
      4.10 Static Forces
      4.11 More Explicit Form

    5.Dynamics
      5.1 Introduction
      5.2 Newton-Euler Formulation
      5.3 Lagrange Forumulation

    6.Trajectory Generation
      6.1 Introduction
      6.2 Joint Space vs. Cartesian Space Planning
      6.3 Path Planning With Polynomial Trajectories
      6.4 Planning with Intermediate Points
      6.5 Straight Paths With Parabolic Blends
      6.6 Generalized Path Planning

    7.Manipulator Control
      7.1 Introduction
      7.2 Passive Natural Systems
      7.3 Passive-Behavior Control
      7.4 Disturbance Rejection
      7.5 Actuation System
      7.6 PD Control for Multi-Link Systems
      7.7 Operational Space Control
      
